linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - gocritic
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - internal/terminal/iterm/proto
