// Trimmed subset of iTerm2's api.proto — only the RPCs used by Atria.
// Source: github.com/gnachman/iTerm2/blob/master/proto/api.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/terminal/iterm/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTabResponse_Status int32

const (
	CreateTabResponse_OK                   CreateTabResponse_Status = 0
	CreateTabResponse_INVALID_PROFILE_NAME CreateTabResponse_Status = 1
	CreateTabResponse_INVALID_WINDOW_ID    CreateTabResponse_Status = 2
	CreateTabResponse_INVALID_TAB_INDEX    CreateTabResponse_Status = 3
	CreateTabResponse_MISSING_SUBSTITUTION CreateTabResponse_Status = 4
)

// Enum value maps for CreateTabResponse_Status.
var (
	CreateTabResponse_Status_name = map[int32]string{
		0: "OK",
		1: "INVALID_PROFILE_NAME",
		2: "INVALID_WINDOW_ID",
		3: "INVALID_TAB_INDEX",
		4: "MISSING_SUBSTITUTION",
	}
	CreateTabResponse_Status_value = map[string]int32{
		"OK":                   0,
		"INVALID_PROFILE_NAME": 1,
		"INVALID_WINDOW_ID":    2,
		"INVALID_TAB_INDEX":    3,
		"MISSING_SUBSTITUTION": 4,
	}
)

func (x CreateTabResponse_Status) Enum() *CreateTabResponse_Status {
	p := new(CreateTabResponse_Status)
	*p = x
	return p
}

func (x CreateTabResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateTabResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_terminal_iterm_proto_api_proto_enumTypes[0].Descriptor()
}

func (CreateTabResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_terminal_iterm_proto_api_proto_enumTypes[0]
}

func (x CreateTabResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CreateTabResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CreateTabResponse_Status(num)
	return nil
}

// Deprecated: Use CreateTabResponse_Status.Descriptor instead.
func (CreateTabResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{8, 0}
}

type SendTextResponse_Status int32

const (
	SendTextResponse_OK                SendTextResponse_Status = 0
	SendTextResponse_SESSION_NOT_FOUND SendTextResponse_Status = 1
)

// Enum value maps for SendTextResponse_Status.
var (
	SendTextResponse_Status_name = map[int32]string{
		0: "OK",
		1: "SESSION_NOT_FOUND",
	}
	SendTextResponse_Status_value = map[string]int32{
		"OK":                0,
		"SESSION_NOT_FOUND": 1,
	}
)

func (x SendTextResponse_Status) Enum() *SendTextResponse_Status {
	p := new(SendTextResponse_Status)
	*p = x
	return p
}

func (x SendTextResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendTextResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_terminal_iterm_proto_api_proto_enumTypes[1].Descriptor()
}

func (SendTextResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_terminal_iterm_proto_api_proto_enumTypes[1]
}

func (x SendTextResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SendTextResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SendTextResponse_Status(num)
	return nil
}

// Deprecated: Use SendTextResponse_Status.Descriptor instead.
func (SendTextResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{10, 0}
}

type ActivateResponse_Status int32

const (
	ActivateResponse_OK             ActivateResponse_Status = 0
	ActivateResponse_BAD_IDENTIFIER ActivateResponse_Status = 1
	ActivateResponse_INVALID_OPTION ActivateResponse_Status = 2
)

// Enum value maps for ActivateResponse_Status.
var (
	ActivateResponse_Status_name = map[int32]string{
		0: "OK",
		1: "BAD_IDENTIFIER",
		2: "INVALID_OPTION",
	}
	ActivateResponse_Status_value = map[string]int32{
		"OK":             0,
		"BAD_IDENTIFIER": 1,
		"INVALID_OPTION": 2,
	}
)

func (x ActivateResponse_Status) Enum() *ActivateResponse_Status {
	p := new(ActivateResponse_Status)
	*p = x
	return p
}

func (x ActivateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_terminal_iterm_proto_api_proto_enumTypes[2].Descriptor()
}

func (ActivateResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_terminal_iterm_proto_api_proto_enumTypes[2]
}

func (x ActivateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActivateResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActivateResponse_Status(num)
	return nil
}

// Deprecated: Use ActivateResponse_Status.Descriptor instead.
func (ActivateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{12, 0}
}

type GetBufferResponse_Status int32

const (
	GetBufferResponse_OK                 GetBufferResponse_Status = 0
	GetBufferResponse_SESSION_NOT_FOUND  GetBufferResponse_Status = 1
	GetBufferResponse_INVALID_LINE_RANGE GetBufferResponse_Status = 2
	GetBufferResponse_REQUEST_MALFORMED  GetBufferResponse_Status = 3
)

// Enum value maps for GetBufferResponse_Status.
var (
	GetBufferResponse_Status_name = map[int32]string{
		0: "OK",
		1: "SESSION_NOT_FOUND",
		2: "INVALID_LINE_RANGE",
		3: "REQUEST_MALFORMED",
	}
	GetBufferResponse_Status_value = map[string]int32{
		"OK":                 0,
		"SESSION_NOT_FOUND":  1,
		"INVALID_LINE_RANGE": 2,
		"REQUEST_MALFORMED":  3,
	}
)

func (x GetBufferResponse_Status) Enum() *GetBufferResponse_Status {
	p := new(GetBufferResponse_Status)
	*p = x
	return p
}

func (x GetBufferResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetBufferResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_terminal_iterm_proto_api_proto_enumTypes[3].Descriptor()
}

func (GetBufferResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_terminal_iterm_proto_api_proto_enumTypes[3]
}

func (x GetBufferResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GetBufferResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GetBufferResponse_Status(num)
	return nil
}

// Deprecated: Use GetBufferResponse_Status.Descriptor instead.
func (GetBufferResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{15, 0}
}

type VariableResponse_Status int32

const (
	VariableResponse_OK                   VariableResponse_Status = 0
	VariableResponse_SESSION_NOT_FOUND    VariableResponse_Status = 1
	VariableResponse_INVALID_NAME         VariableResponse_Status = 2
	VariableResponse_MISSING_SCOPE        VariableResponse_Status = 3
	VariableResponse_TAB_NOT_FOUND        VariableResponse_Status = 4
	VariableResponse_MULTI_GET_DISALLOWED VariableResponse_Status = 5
	VariableResponse_WINDOW_NOT_FOUND     VariableResponse_Status = 6
)

// Enum value maps for VariableResponse_Status.
var (
	VariableResponse_Status_name = map[int32]string{
		0: "OK",
		1: "SESSION_NOT_FOUND",
		2: "INVALID_NAME",
		3: "MISSING_SCOPE",
		4: "TAB_NOT_FOUND",
		5: "MULTI_GET_DISALLOWED",
		6: "WINDOW_NOT_FOUND",
	}
	VariableResponse_Status_value = map[string]int32{
		"OK":                   0,
		"SESSION_NOT_FOUND":    1,
		"INVALID_NAME":         2,
		"MISSING_SCOPE":        3,
		"TAB_NOT_FOUND":        4,
		"MULTI_GET_DISALLOWED": 5,
		"WINDOW_NOT_FOUND":     6,
	}
)

func (x VariableResponse_Status) Enum() *VariableResponse_Status {
	p := new(VariableResponse_Status)
	*p = x
	return p
}

func (x VariableResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_terminal_iterm_proto_api_proto_enumTypes[4].Descriptor()
}

func (VariableResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_terminal_iterm_proto_api_proto_enumTypes[4]
}

func (x VariableResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VariableResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VariableResponse_Status(num)
	return nil
}

// Deprecated: Use VariableResponse_Status.Descriptor instead.
func (VariableResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{18, 0}
}

type FocusChangedNotification_Window_WindowStatus int32

const (
	FocusChangedNotification_Window_TERMINAL_WINDOW_BECAME_KEY   FocusChangedNotification_Window_WindowStatus = 0
	FocusChangedNotification_Window_TERMINAL_WINDOW_IS_CURRENT   FocusChangedNotification_Window_WindowStatus = 1
	FocusChangedNotification_Window_TERMINAL_WINDOW_RESIGNED_KEY FocusChangedNotification_Window_WindowStatus = 2
)

// Enum value maps for FocusChangedNotification_Window_WindowStatus.
var (
	FocusChangedNotification_Window_WindowStatus_name = map[int32]string{
		0: "TERMINAL_WINDOW_BECAME_KEY",
		1: "TERMINAL_WINDOW_IS_CURRENT",
		2: "TERMINAL_WINDOW_RESIGNED_KEY",
	}
	FocusChangedNotification_Window_WindowStatus_value = map[string]int32{
		"TERMINAL_WINDOW_BECAME_KEY":   0,
		"TERMINAL_WINDOW_IS_CURRENT":   1,
		"TERMINAL_WINDOW_RESIGNED_KEY": 2,
	}
)

func (x FocusChangedNotification_Window_WindowStatus) Enum() *FocusChangedNotification_Window_WindowStatus {
	p := new(FocusChangedNotification_Window_WindowStatus)
	*p = x
	return p
}

func (x FocusChangedNotification_Window_WindowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusChangedNotification_Window_WindowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_terminal_iterm_proto_api_proto_enumTypes[5].Descriptor()
}

func (FocusChangedNotification_Window_WindowStatus) Type() protoreflect.EnumType {
	return &file_internal_terminal_iterm_proto_api_proto_enumTypes[5]
}

func (x FocusChangedNotification_Window_WindowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FocusChangedNotification_Window_WindowStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FocusChangedNotification_Window_WindowStatus(num)
	return nil
}

// Deprecated: Use FocusChangedNotification_Window_WindowStatus.Descriptor instead.
func (FocusChangedNotification_Window_WindowStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{21, 0, 0}
}

type ClientOriginatedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Submessage:
	//
	//	*ClientOriginatedMessage_GetBufferRequest
	//	*ClientOriginatedMessage_ListSessionsRequest
	//	*ClientOriginatedMessage_SendTextRequest
	//	*ClientOriginatedMessage_CreateTabRequest
	//	*ClientOriginatedMessage_ActivateRequest
	//	*ClientOriginatedMessage_VariableRequest
	//	*ClientOriginatedMessage_FocusRequest
	Submessage    isClientOriginatedMessage_Submessage `protobuf_oneof:"submessage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOriginatedMessage) Reset() {
	*x = ClientOriginatedMessage{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOriginatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOriginatedMessage) ProtoMessage() {}

func (x *ClientOriginatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOriginatedMessage.ProtoReflect.Descriptor instead.
func (*ClientOriginatedMessage) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ClientOriginatedMessage) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ClientOriginatedMessage) GetSubmessage() isClientOriginatedMessage_Submessage {
	if x != nil {
		return x.Submessage
	}
	return nil
}

func (x *ClientOriginatedMessage) GetGetBufferRequest() *GetBufferRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_GetBufferRequest); ok {
			return x.GetBufferRequest
		}
	}
	return nil
}

func (x *ClientOriginatedMessage) GetListSessionsRequest() *ListSessionsRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_ListSessionsRequest); ok {
			return x.ListSessionsRequest
		}
	}
	return nil
}

func (x *ClientOriginatedMessage) GetSendTextRequest() *SendTextRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_SendTextRequest); ok {
			return x.SendTextRequest
		}
	}
	return nil
}

func (x *ClientOriginatedMessage) GetCreateTabRequest() *CreateTabRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_CreateTabRequest); ok {
			return x.CreateTabRequest
		}
	}
	return nil
}

func (x *ClientOriginatedMessage) GetActivateRequest() *ActivateRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_ActivateRequest); ok {
			return x.ActivateRequest
		}
	}
	return nil
}

func (x *ClientOriginatedMessage) GetVariableRequest() *VariableRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_VariableRequest); ok {
			return x.VariableRequest
		}
	}
	return nil
}

func (x *ClientOriginatedMessage) GetFocusRequest() *FocusRequest {
	if x != nil {
		if x, ok := x.Submessage.(*ClientOriginatedMessage_FocusRequest); ok {
			return x.FocusRequest
		}
	}
	return nil
}

type isClientOriginatedMessage_Submessage interface {
	isClientOriginatedMessage_Submessage()
}

type ClientOriginatedMessage_GetBufferRequest struct {
	GetBufferRequest *GetBufferRequest `protobuf:"bytes,100,opt,name=get_buffer_request,json=getBufferRequest,oneof"`
}

type ClientOriginatedMessage_ListSessionsRequest struct {
	ListSessionsRequest *ListSessionsRequest `protobuf:"bytes,106,opt,name=list_sessions_request,json=listSessionsRequest,oneof"`
}

type ClientOriginatedMessage_SendTextRequest struct {
	SendTextRequest *SendTextRequest `protobuf:"bytes,107,opt,name=send_text_request,json=sendTextRequest,oneof"`
}

type ClientOriginatedMessage_CreateTabRequest struct {
	CreateTabRequest *CreateTabRequest `protobuf:"bytes,108,opt,name=create_tab_request,json=createTabRequest,oneof"`
}

type ClientOriginatedMessage_ActivateRequest struct {
	ActivateRequest *ActivateRequest `protobuf:"bytes,114,opt,name=activate_request,json=activateRequest,oneof"`
}

type ClientOriginatedMessage_VariableRequest struct {
	VariableRequest *VariableRequest `protobuf:"bytes,115,opt,name=variable_request,json=variableRequest,oneof"`
}

type ClientOriginatedMessage_FocusRequest struct {
	FocusRequest *FocusRequest `protobuf:"bytes,117,opt,name=focus_request,json=focusRequest,oneof"`
}

func (*ClientOriginatedMessage_GetBufferRequest) isClientOriginatedMessage_Submessage() {}

func (*ClientOriginatedMessage_ListSessionsRequest) isClientOriginatedMessage_Submessage() {}

func (*ClientOriginatedMessage_SendTextRequest) isClientOriginatedMessage_Submessage() {}

func (*ClientOriginatedMessage_CreateTabRequest) isClientOriginatedMessage_Submessage() {}

func (*ClientOriginatedMessage_ActivateRequest) isClientOriginatedMessage_Submessage() {}

func (*ClientOriginatedMessage_VariableRequest) isClientOriginatedMessage_Submessage() {}

func (*ClientOriginatedMessage_FocusRequest) isClientOriginatedMessage_Submessage() {}

type ServerOriginatedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Submessage:
	//
	//	*ServerOriginatedMessage_Error
	//	*ServerOriginatedMessage_GetBufferResponse
	//	*ServerOriginatedMessage_ListSessionsResponse
	//	*ServerOriginatedMessage_SendTextResponse
	//	*ServerOriginatedMessage_CreateTabResponse
	//	*ServerOriginatedMessage_ActivateResponse
	//	*ServerOriginatedMessage_VariableResponse
	//	*ServerOriginatedMessage_FocusResponse
	//	*ServerOriginatedMessage_Notification
	Submessage    isServerOriginatedMessage_Submessage `protobuf_oneof:"submessage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerOriginatedMessage) Reset() {
	*x = ServerOriginatedMessage{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerOriginatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerOriginatedMessage) ProtoMessage() {}

func (x *ServerOriginatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerOriginatedMessage.ProtoReflect.Descriptor instead.
func (*ServerOriginatedMessage) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ServerOriginatedMessage) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ServerOriginatedMessage) GetSubmessage() isServerOriginatedMessage_Submessage {
	if x != nil {
		return x.Submessage
	}
	return nil
}

func (x *ServerOriginatedMessage) GetError() string {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ServerOriginatedMessage) GetGetBufferResponse() *GetBufferResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_GetBufferResponse); ok {
			return x.GetBufferResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetListSessionsResponse() *ListSessionsResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_ListSessionsResponse); ok {
			return x.ListSessionsResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetSendTextResponse() *SendTextResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_SendTextResponse); ok {
			return x.SendTextResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetCreateTabResponse() *CreateTabResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_CreateTabResponse); ok {
			return x.CreateTabResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetActivateResponse() *ActivateResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_ActivateResponse); ok {
			return x.ActivateResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetVariableResponse() *VariableResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_VariableResponse); ok {
			return x.VariableResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetFocusResponse() *FocusResponse {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_FocusResponse); ok {
			return x.FocusResponse
		}
	}
	return nil
}

func (x *ServerOriginatedMessage) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.Submessage.(*ServerOriginatedMessage_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isServerOriginatedMessage_Submessage interface {
	isServerOriginatedMessage_Submessage()
}

type ServerOriginatedMessage_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,oneof"`
}

type ServerOriginatedMessage_GetBufferResponse struct {
	GetBufferResponse *GetBufferResponse `protobuf:"bytes,100,opt,name=get_buffer_response,json=getBufferResponse,oneof"`
}

type ServerOriginatedMessage_ListSessionsResponse struct {
	ListSessionsResponse *ListSessionsResponse `protobuf:"bytes,106,opt,name=list_sessions_response,json=listSessionsResponse,oneof"`
}

type ServerOriginatedMessage_SendTextResponse struct {
	SendTextResponse *SendTextResponse `protobuf:"bytes,107,opt,name=send_text_response,json=sendTextResponse,oneof"`
}

type ServerOriginatedMessage_CreateTabResponse struct {
	CreateTabResponse *CreateTabResponse `protobuf:"bytes,108,opt,name=create_tab_response,json=createTabResponse,oneof"`
}

type ServerOriginatedMessage_ActivateResponse struct {
	ActivateResponse *ActivateResponse `protobuf:"bytes,114,opt,name=activate_response,json=activateResponse,oneof"`
}

type ServerOriginatedMessage_VariableResponse struct {
	VariableResponse *VariableResponse `protobuf:"bytes,115,opt,name=variable_response,json=variableResponse,oneof"`
}

type ServerOriginatedMessage_FocusResponse struct {
	FocusResponse *FocusResponse `protobuf:"bytes,117,opt,name=focus_response,json=focusResponse,oneof"`
}

type ServerOriginatedMessage_Notification struct {
	Notification *Notification `protobuf:"bytes,1000,opt,name=notification,oneof"`
}

func (*ServerOriginatedMessage_Error) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_GetBufferResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_ListSessionsResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_SendTextResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_CreateTabResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_ActivateResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_VariableResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_FocusResponse) isServerOriginatedMessage_Submessage() {}

func (*ServerOriginatedMessage_Notification) isServerOriginatedMessage_Submessage() {}

// Notification is included only so ServerOriginatedMessage compiles.
// Atria does not subscribe to notifications.
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{2}
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{3}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Windows       []*ListSessionsResponse_Window `protobuf:"bytes,1,rep,name=windows" json:"windows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsResponse) GetWindows() []*ListSessionsResponse_Window {
	if x != nil {
		return x.Windows
	}
	return nil
}

type SplitTreeNode struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Vertical      *bool                          `protobuf:"varint,1,opt,name=vertical" json:"vertical,omitempty"`
	Links         []*SplitTreeNode_SplitTreeLink `protobuf:"bytes,2,rep,name=links" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitTreeNode) Reset() {
	*x = SplitTreeNode{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitTreeNode) ProtoMessage() {}

func (x *SplitTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitTreeNode.ProtoReflect.Descriptor instead.
func (*SplitTreeNode) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *SplitTreeNode) GetVertical() bool {
	if x != nil && x.Vertical != nil {
		return *x.Vertical
	}
	return false
}

func (x *SplitTreeNode) GetLinks() []*SplitTreeNode_SplitTreeLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type SessionSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UniqueIdentifier *string                `protobuf:"bytes,1,opt,name=unique_identifier,json=uniqueIdentifier" json:"unique_identifier,omitempty"`
	Title            *string                `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *SessionSummary) GetUniqueIdentifier() string {
	if x != nil && x.UniqueIdentifier != nil {
		return *x.UniqueIdentifier
	}
	return ""
}

func (x *SessionSummary) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type CreateTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileName   *string                `protobuf:"bytes,1,opt,name=profile_name,json=profileName" json:"profile_name,omitempty"`
	WindowId      *string                `protobuf:"bytes,2,opt,name=window_id,json=windowId" json:"window_id,omitempty"`
	TabIndex      *uint32                `protobuf:"varint,3,opt,name=tab_index,json=tabIndex" json:"tab_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTabRequest) Reset() {
	*x = CreateTabRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTabRequest) ProtoMessage() {}

func (x *CreateTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTabRequest.ProtoReflect.Descriptor instead.
func (*CreateTabRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTabRequest) GetProfileName() string {
	if x != nil && x.ProfileName != nil {
		return *x.ProfileName
	}
	return ""
}

func (x *CreateTabRequest) GetWindowId() string {
	if x != nil && x.WindowId != nil {
		return *x.WindowId
	}
	return ""
}

func (x *CreateTabRequest) GetTabIndex() uint32 {
	if x != nil && x.TabIndex != nil {
		return *x.TabIndex
	}
	return 0
}

type CreateTabResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        *CreateTabResponse_Status `protobuf:"varint,1,opt,name=status,enum=iterm2.CreateTabResponse_Status" json:"status,omitempty"`
	WindowId      *string                   `protobuf:"bytes,2,opt,name=window_id,json=windowId" json:"window_id,omitempty"`
	TabId         *int32                    `protobuf:"varint,3,opt,name=tab_id,json=tabId" json:"tab_id,omitempty"`
	SessionId     *string                   `protobuf:"bytes,4,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTabResponse) Reset() {
	*x = CreateTabResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTabResponse) ProtoMessage() {}

func (x *CreateTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTabResponse.ProtoReflect.Descriptor instead.
func (*CreateTabResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTabResponse) GetStatus() CreateTabResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CreateTabResponse_OK
}

func (x *CreateTabResponse) GetWindowId() string {
	if x != nil && x.WindowId != nil {
		return *x.WindowId
	}
	return ""
}

func (x *CreateTabResponse) GetTabId() int32 {
	if x != nil && x.TabId != nil {
		return *x.TabId
	}
	return 0
}

func (x *CreateTabResponse) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

type SendTextRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Session           *string                `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Text              *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	SuppressBroadcast *bool                  `protobuf:"varint,3,opt,name=suppress_broadcast,json=suppressBroadcast" json:"suppress_broadcast,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *SendTextRequest) GetSession() string {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return ""
}

func (x *SendTextRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *SendTextRequest) GetSuppressBroadcast() bool {
	if x != nil && x.SuppressBroadcast != nil {
		return *x.SuppressBroadcast
	}
	return false
}

type SendTextResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *SendTextResponse_Status `protobuf:"varint,1,opt,name=status,enum=iterm2.SendTextResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextResponse) Reset() {
	*x = SendTextResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextResponse) ProtoMessage() {}

func (x *SendTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextResponse.ProtoReflect.Descriptor instead.
func (*SendTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *SendTextResponse) GetStatus() SendTextResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return SendTextResponse_OK
}

type ActivateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*ActivateRequest_WindowId
	//	*ActivateRequest_TabId
	//	*ActivateRequest_SessionId
	Identifier       isActivateRequest_Identifier `protobuf_oneof:"identifier"`
	OrderWindowFront *bool                        `protobuf:"varint,4,opt,name=order_window_front,json=orderWindowFront" json:"order_window_front,omitempty"`
	SelectTab        *bool                        `protobuf:"varint,5,opt,name=select_tab,json=selectTab" json:"select_tab,omitempty"`
	SelectSession    *bool                        `protobuf:"varint,6,opt,name=select_session,json=selectSession" json:"select_session,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateRequest) GetIdentifier() isActivateRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ActivateRequest) GetWindowId() string {
	if x != nil {
		if x, ok := x.Identifier.(*ActivateRequest_WindowId); ok {
			return x.WindowId
		}
	}
	return ""
}

func (x *ActivateRequest) GetTabId() string {
	if x != nil {
		if x, ok := x.Identifier.(*ActivateRequest_TabId); ok {
			return x.TabId
		}
	}
	return ""
}

func (x *ActivateRequest) GetSessionId() string {
	if x != nil {
		if x, ok := x.Identifier.(*ActivateRequest_SessionId); ok {
			return x.SessionId
		}
	}
	return ""
}

func (x *ActivateRequest) GetOrderWindowFront() bool {
	if x != nil && x.OrderWindowFront != nil {
		return *x.OrderWindowFront
	}
	return false
}

func (x *ActivateRequest) GetSelectTab() bool {
	if x != nil && x.SelectTab != nil {
		return *x.SelectTab
	}
	return false
}

func (x *ActivateRequest) GetSelectSession() bool {
	if x != nil && x.SelectSession != nil {
		return *x.SelectSession
	}
	return false
}

type isActivateRequest_Identifier interface {
	isActivateRequest_Identifier()
}

type ActivateRequest_WindowId struct {
	WindowId string `protobuf:"bytes,1,opt,name=window_id,json=windowId,oneof"`
}

type ActivateRequest_TabId struct {
	TabId string `protobuf:"bytes,2,opt,name=tab_id,json=tabId,oneof"`
}

type ActivateRequest_SessionId struct {
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,oneof"`
}

func (*ActivateRequest_WindowId) isActivateRequest_Identifier() {}

func (*ActivateRequest_TabId) isActivateRequest_Identifier() {}

func (*ActivateRequest_SessionId) isActivateRequest_Identifier() {}

type ActivateResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *ActivateResponse_Status `protobuf:"varint,1,opt,name=status,enum=iterm2.ActivateResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ActivateResponse) GetStatus() ActivateResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ActivateResponse_OK
}

type GetBufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *string                `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	LineRange     *LineRange             `protobuf:"bytes,2,opt,name=line_range,json=lineRange" json:"line_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBufferRequest) Reset() {
	*x = GetBufferRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBufferRequest) ProtoMessage() {}

func (x *GetBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBufferRequest.ProtoReflect.Descriptor instead.
func (*GetBufferRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetBufferRequest) GetSession() string {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return ""
}

func (x *GetBufferRequest) GetLineRange() *LineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

type LineRange struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScreenContentsOnly *bool                  `protobuf:"varint,1,opt,name=screen_contents_only,json=screenContentsOnly" json:"screen_contents_only,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LineRange) Reset() {
	*x = LineRange{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineRange) ProtoMessage() {}

func (x *LineRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineRange.ProtoReflect.Descriptor instead.
func (*LineRange) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *LineRange) GetScreenContentsOnly() bool {
	if x != nil && x.ScreenContentsOnly != nil {
		return *x.ScreenContentsOnly
	}
	return false
}

type GetBufferResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        *GetBufferResponse_Status `protobuf:"varint,1,opt,name=status,enum=iterm2.GetBufferResponse_Status,def=0" json:"status,omitempty"`
	Contents      []*LineContents           `protobuf:"bytes,3,rep,name=contents" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for GetBufferResponse fields.
const (
	Default_GetBufferResponse_Status = GetBufferResponse_OK
)

func (x *GetBufferResponse) Reset() {
	*x = GetBufferResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBufferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBufferResponse) ProtoMessage() {}

func (x *GetBufferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBufferResponse.ProtoReflect.Descriptor instead.
func (*GetBufferResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetBufferResponse) GetStatus() GetBufferResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Default_GetBufferResponse_Status
}

func (x *GetBufferResponse) GetContents() []*LineContents {
	if x != nil {
		return x.Contents
	}
	return nil
}

type LineContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineContents) Reset() {
	*x = LineContents{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineContents) ProtoMessage() {}

func (x *LineContents) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineContents.ProtoReflect.Descriptor instead.
func (*LineContents) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *LineContents) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type VariableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*VariableRequest_SessionId
	//	*VariableRequest_TabId
	//	*VariableRequest_App
	//	*VariableRequest_WindowId
	Scope         isVariableRequest_Scope `protobuf_oneof:"scope"`
	Get           []string                `protobuf:"bytes,3,rep,name=get" json:"get,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableRequest) Reset() {
	*x = VariableRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableRequest) ProtoMessage() {}

func (x *VariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableRequest.ProtoReflect.Descriptor instead.
func (*VariableRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *VariableRequest) GetScope() isVariableRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *VariableRequest) GetSessionId() string {
	if x != nil {
		if x, ok := x.Scope.(*VariableRequest_SessionId); ok {
			return x.SessionId
		}
	}
	return ""
}

func (x *VariableRequest) GetTabId() string {
	if x != nil {
		if x, ok := x.Scope.(*VariableRequest_TabId); ok {
			return x.TabId
		}
	}
	return ""
}

func (x *VariableRequest) GetApp() bool {
	if x != nil {
		if x, ok := x.Scope.(*VariableRequest_App); ok {
			return x.App
		}
	}
	return false
}

func (x *VariableRequest) GetWindowId() string {
	if x != nil {
		if x, ok := x.Scope.(*VariableRequest_WindowId); ok {
			return x.WindowId
		}
	}
	return ""
}

func (x *VariableRequest) GetGet() []string {
	if x != nil {
		return x.Get
	}
	return nil
}

type isVariableRequest_Scope interface {
	isVariableRequest_Scope()
}

type VariableRequest_SessionId struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,oneof"`
}

type VariableRequest_TabId struct {
	TabId string `protobuf:"bytes,4,opt,name=tab_id,json=tabId,oneof"`
}

type VariableRequest_App struct {
	App bool `protobuf:"varint,5,opt,name=app,oneof"`
}

type VariableRequest_WindowId struct {
	WindowId string `protobuf:"bytes,6,opt,name=window_id,json=windowId,oneof"`
}

func (*VariableRequest_SessionId) isVariableRequest_Scope() {}

func (*VariableRequest_TabId) isVariableRequest_Scope() {}

func (*VariableRequest_App) isVariableRequest_Scope() {}

func (*VariableRequest_WindowId) isVariableRequest_Scope() {}

type VariableResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        *VariableResponse_Status `protobuf:"varint,1,opt,name=status,enum=iterm2.VariableResponse_Status" json:"status,omitempty"`
	Values        []string                 `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableResponse) Reset() {
	*x = VariableResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableResponse) ProtoMessage() {}

func (x *VariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableResponse.ProtoReflect.Descriptor instead.
func (*VariableResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{18}
}

func (x *VariableResponse) GetStatus() VariableResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return VariableResponse_OK
}

func (x *VariableResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type FocusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusRequest) Reset() {
	*x = FocusRequest{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusRequest) ProtoMessage() {}

func (x *FocusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusRequest.ProtoReflect.Descriptor instead.
func (*FocusRequest) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{19}
}

type FocusResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Notifications []*FocusChangedNotification `protobuf:"bytes,1,rep,name=notifications" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusResponse) Reset() {
	*x = FocusResponse{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusResponse) ProtoMessage() {}

func (x *FocusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusResponse.ProtoReflect.Descriptor instead.
func (*FocusResponse) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{20}
}

func (x *FocusResponse) GetNotifications() []*FocusChangedNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type FocusChangedNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*FocusChangedNotification_ApplicationActive
	//	*FocusChangedNotification_Window_
	//	*FocusChangedNotification_SelectedTab
	//	*FocusChangedNotification_Session
	Event         isFocusChangedNotification_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusChangedNotification) Reset() {
	*x = FocusChangedNotification{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusChangedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusChangedNotification) ProtoMessage() {}

func (x *FocusChangedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusChangedNotification.ProtoReflect.Descriptor instead.
func (*FocusChangedNotification) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{21}
}

func (x *FocusChangedNotification) GetEvent() isFocusChangedNotification_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *FocusChangedNotification) GetApplicationActive() bool {
	if x != nil {
		if x, ok := x.Event.(*FocusChangedNotification_ApplicationActive); ok {
			return x.ApplicationActive
		}
	}
	return false
}

func (x *FocusChangedNotification) GetWindow() *FocusChangedNotification_Window {
	if x != nil {
		if x, ok := x.Event.(*FocusChangedNotification_Window_); ok {
			return x.Window
		}
	}
	return nil
}

func (x *FocusChangedNotification) GetSelectedTab() string {
	if x != nil {
		if x, ok := x.Event.(*FocusChangedNotification_SelectedTab); ok {
			return x.SelectedTab
		}
	}
	return ""
}

func (x *FocusChangedNotification) GetSession() string {
	if x != nil {
		if x, ok := x.Event.(*FocusChangedNotification_Session); ok {
			return x.Session
		}
	}
	return ""
}

type isFocusChangedNotification_Event interface {
	isFocusChangedNotification_Event()
}

type FocusChangedNotification_ApplicationActive struct {
	ApplicationActive bool `protobuf:"varint,1,opt,name=application_active,json=applicationActive,oneof"`
}

type FocusChangedNotification_Window_ struct {
	Window *FocusChangedNotification_Window `protobuf:"bytes,2,opt,name=window,oneof"`
}

type FocusChangedNotification_SelectedTab struct {
	SelectedTab string `protobuf:"bytes,3,opt,name=selected_tab,json=selectedTab,oneof"`
}

type FocusChangedNotification_Session struct {
	Session string `protobuf:"bytes,4,opt,name=session,oneof"`
}

func (*FocusChangedNotification_ApplicationActive) isFocusChangedNotification_Event() {}

func (*FocusChangedNotification_Window_) isFocusChangedNotification_Event() {}

func (*FocusChangedNotification_SelectedTab) isFocusChangedNotification_Event() {}

func (*FocusChangedNotification_Session) isFocusChangedNotification_Event() {}

type ListSessionsResponse_Window struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Tabs          []*ListSessionsResponse_Tab `protobuf:"bytes,1,rep,name=tabs" json:"tabs,omitempty"`
	WindowId      *string                     `protobuf:"bytes,2,opt,name=window_id,json=windowId" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse_Window) Reset() {
	*x = ListSessionsResponse_Window{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse_Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse_Window) ProtoMessage() {}

func (x *ListSessionsResponse_Window) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse_Window.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse_Window) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListSessionsResponse_Window) GetTabs() []*ListSessionsResponse_Tab {
	if x != nil {
		return x.Tabs
	}
	return nil
}

func (x *ListSessionsResponse_Window) GetWindowId() string {
	if x != nil && x.WindowId != nil {
		return *x.WindowId
	}
	return ""
}

type ListSessionsResponse_Tab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *SplitTreeNode         `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
	TabId         *string                `protobuf:"bytes,2,opt,name=tab_id,json=tabId" json:"tab_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse_Tab) Reset() {
	*x = ListSessionsResponse_Tab{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse_Tab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse_Tab) ProtoMessage() {}

func (x *ListSessionsResponse_Tab) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse_Tab.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse_Tab) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ListSessionsResponse_Tab) GetRoot() *SplitTreeNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ListSessionsResponse_Tab) GetTabId() string {
	if x != nil && x.TabId != nil {
		return *x.TabId
	}
	return ""
}

type SplitTreeNode_SplitTreeLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Child:
	//
	//	*SplitTreeNode_SplitTreeLink_Session
	//	*SplitTreeNode_SplitTreeLink_Node
	Child         isSplitTreeNode_SplitTreeLink_Child `protobuf_oneof:"child"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitTreeNode_SplitTreeLink) Reset() {
	*x = SplitTreeNode_SplitTreeLink{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitTreeNode_SplitTreeLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitTreeNode_SplitTreeLink) ProtoMessage() {}

func (x *SplitTreeNode_SplitTreeLink) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitTreeNode_SplitTreeLink.ProtoReflect.Descriptor instead.
func (*SplitTreeNode_SplitTreeLink) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SplitTreeNode_SplitTreeLink) GetChild() isSplitTreeNode_SplitTreeLink_Child {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *SplitTreeNode_SplitTreeLink) GetSession() *SessionSummary {
	if x != nil {
		if x, ok := x.Child.(*SplitTreeNode_SplitTreeLink_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *SplitTreeNode_SplitTreeLink) GetNode() *SplitTreeNode {
	if x != nil {
		if x, ok := x.Child.(*SplitTreeNode_SplitTreeLink_Node); ok {
			return x.Node
		}
	}
	return nil
}

type isSplitTreeNode_SplitTreeLink_Child interface {
	isSplitTreeNode_SplitTreeLink_Child()
}

type SplitTreeNode_SplitTreeLink_Session struct {
	Session *SessionSummary `protobuf:"bytes,1,opt,name=session,oneof"`
}

type SplitTreeNode_SplitTreeLink_Node struct {
	Node *SplitTreeNode `protobuf:"bytes,2,opt,name=node,oneof"`
}

func (*SplitTreeNode_SplitTreeLink_Session) isSplitTreeNode_SplitTreeLink_Child() {}

func (*SplitTreeNode_SplitTreeLink_Node) isSplitTreeNode_SplitTreeLink_Child() {}

type FocusChangedNotification_Window struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	WindowStatus  *FocusChangedNotification_Window_WindowStatus `protobuf:"varint,1,opt,name=window_status,json=windowStatus,enum=iterm2.FocusChangedNotification_Window_WindowStatus" json:"window_status,omitempty"`
	WindowId      *string                                       `protobuf:"bytes,2,opt,name=window_id,json=windowId" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusChangedNotification_Window) Reset() {
	*x = FocusChangedNotification_Window{}
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusChangedNotification_Window) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusChangedNotification_Window) ProtoMessage() {}

func (x *FocusChangedNotification_Window) ProtoReflect() protoreflect.Message {
	mi := &file_internal_terminal_iterm_proto_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusChangedNotification_Window.ProtoReflect.Descriptor instead.
func (*FocusChangedNotification_Window) Descriptor() ([]byte, []int) {
	return file_internal_terminal_iterm_proto_api_proto_rawDescGZIP(), []int{21, 0}
}

func (x *FocusChangedNotification_Window) GetWindowStatus() FocusChangedNotification_Window_WindowStatus {
	if x != nil && x.WindowStatus != nil {
		return *x.WindowStatus
	}
	return FocusChangedNotification_Window_TERMINAL_WINDOW_BECAME_KEY
}

func (x *FocusChangedNotification_Window) GetWindowId() string {
	if x != nil && x.WindowId != nil {
		return *x.WindowId
	}
	return ""
}

var File_internal_terminal_iterm_proto_api_proto protoreflect.FileDescriptor

const file_internal_terminal_iterm_proto_api_proto_rawDesc = "" +
	"\n" +
	"'internal/terminal/iterm/proto/api.proto\x12\x06iterm2\"\xae\x04\n" +
	"\x17ClientOriginatedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12H\n" +
	"\x12get_buffer_request\x18d \x01(\v2\x18.iterm2.GetBufferRequestH\x00R\x10getBufferRequest\x12Q\n" +
	"\x15list_sessions_request\x18j \x01(\v2\x1b.iterm2.ListSessionsRequestH\x00R\x13listSessionsRequest\x12E\n" +
	"\x11send_text_request\x18k \x01(\v2\x17.iterm2.SendTextRequestH\x00R\x0fsendTextRequest\x12H\n" +
	"\x12create_tab_request\x18l \x01(\v2\x18.iterm2.CreateTabRequestH\x00R\x10createTabRequest\x12D\n" +
	"\x10activate_request\x18r \x01(\v2\x17.iterm2.ActivateRequestH\x00R\x0factivateRequest\x12D\n" +
	"\x10variable_request\x18s \x01(\v2\x17.iterm2.VariableRequestH\x00R\x0fvariableRequest\x12;\n" +
	"\rfocus_request\x18u \x01(\v2\x14.iterm2.FocusRequestH\x00R\ffocusRequestB\f\n" +
	"\n" +
	"submessage\"\x98\x05\n" +
	"\x17ServerOriginatedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12K\n" +
	"\x13get_buffer_response\x18d \x01(\v2\x19.iterm2.GetBufferResponseH\x00R\x11getBufferResponse\x12T\n" +
	"\x16list_sessions_response\x18j \x01(\v2\x1c.iterm2.ListSessionsResponseH\x00R\x14listSessionsResponse\x12H\n" +
	"\x12send_text_response\x18k \x01(\v2\x18.iterm2.SendTextResponseH\x00R\x10sendTextResponse\x12K\n" +
	"\x13create_tab_response\x18l \x01(\v2\x19.iterm2.CreateTabResponseH\x00R\x11createTabResponse\x12G\n" +
	"\x11activate_response\x18r \x01(\v2\x18.iterm2.ActivateResponseH\x00R\x10activateResponse\x12G\n" +
	"\x11variable_response\x18s \x01(\v2\x18.iterm2.VariableResponseH\x00R\x10variableResponse\x12>\n" +
	"\x0efocus_response\x18u \x01(\v2\x15.iterm2.FocusResponseH\x00R\rfocusResponse\x12;\n" +
	"\fnotification\x18\xe8\a \x01(\v2\x14.iterm2.NotificationH\x00R\fnotificationB\f\n" +
	"\n" +
	"submessage\"\x0e\n" +
	"\fNotification\"\x15\n" +
	"\x13ListSessionsRequest\"\xfb\x01\n" +
	"\x14ListSessionsResponse\x12=\n" +
	"\awindows\x18\x01 \x03(\v2#.iterm2.ListSessionsResponse.WindowR\awindows\x1a[\n" +
	"\x06Window\x124\n" +
	"\x04tabs\x18\x01 \x03(\v2 .iterm2.ListSessionsResponse.TabR\x04tabs\x12\x1b\n" +
	"\twindow_id\x18\x02 \x01(\tR\bwindowId\x1aG\n" +
	"\x03Tab\x12)\n" +
	"\x04root\x18\x03 \x01(\v2\x15.iterm2.SplitTreeNodeR\x04root\x12\x15\n" +
	"\x06tab_id\x18\x02 \x01(\tR\x05tabId\"\xe1\x01\n" +
	"\rSplitTreeNode\x12\x1a\n" +
	"\bvertical\x18\x01 \x01(\bR\bvertical\x129\n" +
	"\x05links\x18\x02 \x03(\v2#.iterm2.SplitTreeNode.SplitTreeLinkR\x05links\x1ay\n" +
	"\rSplitTreeLink\x122\n" +
	"\asession\x18\x01 \x01(\v2\x16.iterm2.SessionSummaryH\x00R\asession\x12+\n" +
	"\x04node\x18\x02 \x01(\v2\x15.iterm2.SplitTreeNodeH\x00R\x04nodeB\a\n" +
	"\x05child\"S\n" +
	"\x0eSessionSummary\x12+\n" +
	"\x11unique_identifier\x18\x01 \x01(\tR\x10uniqueIdentifier\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"o\n" +
	"\x10CreateTabRequest\x12!\n" +
	"\fprofile_name\x18\x01 \x01(\tR\vprofileName\x12\x1b\n" +
	"\twindow_id\x18\x02 \x01(\tR\bwindowId\x12\x1b\n" +
	"\ttab_index\x18\x03 \x01(\rR\btabIndex\"\x94\x02\n" +
	"\x11CreateTabResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .iterm2.CreateTabResponse.StatusR\x06status\x12\x1b\n" +
	"\twindow_id\x18\x02 \x01(\tR\bwindowId\x12\x15\n" +
	"\x06tab_id\x18\x03 \x01(\x05R\x05tabId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"r\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x18\n" +
	"\x14INVALID_PROFILE_NAME\x10\x01\x12\x15\n" +
	"\x11INVALID_WINDOW_ID\x10\x02\x12\x15\n" +
	"\x11INVALID_TAB_INDEX\x10\x03\x12\x18\n" +
	"\x14MISSING_SUBSTITUTION\x10\x04\"n\n" +
	"\x0fSendTextRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12-\n" +
	"\x12suppress_broadcast\x18\x03 \x01(\bR\x11suppressBroadcast\"t\n" +
	"\x10SendTextResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.iterm2.SendTextResponse.StatusR\x06status\"'\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x15\n" +
	"\x11SESSION_NOT_FOUND\x10\x01\"\xec\x01\n" +
	"\x0fActivateRequest\x12\x1d\n" +
	"\twindow_id\x18\x01 \x01(\tH\x00R\bwindowId\x12\x17\n" +
	"\x06tab_id\x18\x02 \x01(\tH\x00R\x05tabId\x12\x1f\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tH\x00R\tsessionId\x12,\n" +
	"\x12order_window_front\x18\x04 \x01(\bR\x10orderWindowFront\x12\x1d\n" +
	"\n" +
	"select_tab\x18\x05 \x01(\bR\tselectTab\x12%\n" +
	"\x0eselect_session\x18\x06 \x01(\bR\rselectSessionB\f\n" +
	"\n" +
	"identifier\"\x85\x01\n" +
	"\x10ActivateResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.iterm2.ActivateResponse.StatusR\x06status\"8\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x12\n" +
	"\x0eBAD_IDENTIFIER\x10\x01\x12\x12\n" +
	"\x0eINVALID_OPTION\x10\x02\"^\n" +
	"\x10GetBufferRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x120\n" +
	"\n" +
	"line_range\x18\x02 \x01(\v2\x11.iterm2.LineRangeR\tlineRange\"=\n" +
	"\tLineRange\x120\n" +
	"\x14screen_contents_only\x18\x01 \x01(\bR\x12screenContentsOnly\"\xdb\x01\n" +
	"\x11GetBufferResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2 .iterm2.GetBufferResponse.Status:\x02OKR\x06status\x120\n" +
	"\bcontents\x18\x03 \x03(\v2\x14.iterm2.LineContentsR\bcontents\"V\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x15\n" +
	"\x11SESSION_NOT_FOUND\x10\x01\x12\x16\n" +
	"\x12INVALID_LINE_RANGE\x10\x02\x12\x15\n" +
	"\x11REQUEST_MALFORMED\x10\x03\"\"\n" +
	"\fLineContents\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x99\x01\n" +
	"\x0fVariableRequest\x12\x1f\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x12\x17\n" +
	"\x06tab_id\x18\x04 \x01(\tH\x00R\x05tabId\x12\x12\n" +
	"\x03app\x18\x05 \x01(\bH\x00R\x03app\x12\x1d\n" +
	"\twindow_id\x18\x06 \x01(\tH\x00R\bwindowId\x12\x10\n" +
	"\x03get\x18\x03 \x03(\tR\x03getB\a\n" +
	"\x05scope\"\xf5\x01\n" +
	"\x10VariableResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.iterm2.VariableResponse.StatusR\x06status\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x8f\x01\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x15\n" +
	"\x11SESSION_NOT_FOUND\x10\x01\x12\x10\n" +
	"\fINVALID_NAME\x10\x02\x12\x11\n" +
	"\rMISSING_SCOPE\x10\x03\x12\x11\n" +
	"\rTAB_NOT_FOUND\x10\x04\x12\x18\n" +
	"\x14MULTI_GET_DISALLOWED\x10\x05\x12\x14\n" +
	"\x10WINDOW_NOT_FOUND\x10\x06\"\x0e\n" +
	"\fFocusRequest\"W\n" +
	"\rFocusResponse\x12F\n" +
	"\rnotifications\x18\x01 \x03(\v2 .iterm2.FocusChangedNotificationR\rnotifications\"\xcd\x03\n" +
	"\x18FocusChangedNotification\x12/\n" +
	"\x12application_active\x18\x01 \x01(\bH\x00R\x11applicationActive\x12A\n" +
	"\x06window\x18\x02 \x01(\v2'.iterm2.FocusChangedNotification.WindowH\x00R\x06window\x12#\n" +
	"\fselected_tab\x18\x03 \x01(\tH\x00R\vselectedTab\x12\x1a\n" +
	"\asession\x18\x04 \x01(\tH\x00R\asession\x1a\xf2\x01\n" +
	"\x06Window\x12Y\n" +
	"\rwindow_status\x18\x01 \x01(\x0e24.iterm2.FocusChangedNotification.Window.WindowStatusR\fwindowStatus\x12\x1b\n" +
	"\twindow_id\x18\x02 \x01(\tR\bwindowId\"p\n" +
	"\fWindowStatus\x12\x1e\n" +
	"\x1aTERMINAL_WINDOW_BECAME_KEY\x10\x00\x12\x1e\n" +
	"\x1aTERMINAL_WINDOW_IS_CURRENT\x10\x01\x12 \n" +
	"\x1cTERMINAL_WINDOW_RESIGNED_KEY\x10\x02B\a\n" +
	"\x05eventB<Z:github.com/sethdeckard/atria/internal/terminal/iterm/proto"

var (
	file_internal_terminal_iterm_proto_api_proto_rawDescOnce sync.Once
	file_internal_terminal_iterm_proto_api_proto_rawDescData []byte
)

func file_internal_terminal_iterm_proto_api_proto_rawDescGZIP() []byte {
	file_internal_terminal_iterm_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_terminal_iterm_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_terminal_iterm_proto_api_proto_rawDesc), len(file_internal_terminal_iterm_proto_api_proto_rawDesc)))
	})
	return file_internal_terminal_iterm_proto_api_proto_rawDescData
}

var file_internal_terminal_iterm_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_internal_terminal_iterm_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_terminal_iterm_proto_api_proto_goTypes = []any{
	(CreateTabResponse_Status)(0),                     // 0: iterm2.CreateTabResponse.Status
	(SendTextResponse_Status)(0),                      // 1: iterm2.SendTextResponse.Status
	(ActivateResponse_Status)(0),                      // 2: iterm2.ActivateResponse.Status
	(GetBufferResponse_Status)(0),                     // 3: iterm2.GetBufferResponse.Status
	(VariableResponse_Status)(0),                      // 4: iterm2.VariableResponse.Status
	(FocusChangedNotification_Window_WindowStatus)(0), // 5: iterm2.FocusChangedNotification.Window.WindowStatus
	(*ClientOriginatedMessage)(nil),                   // 6: iterm2.ClientOriginatedMessage
	(*ServerOriginatedMessage)(nil),                   // 7: iterm2.ServerOriginatedMessage
	(*Notification)(nil),                              // 8: iterm2.Notification
	(*ListSessionsRequest)(nil),                       // 9: iterm2.ListSessionsRequest
	(*ListSessionsResponse)(nil),                      // 10: iterm2.ListSessionsResponse
	(*SplitTreeNode)(nil),                             // 11: iterm2.SplitTreeNode
	(*SessionSummary)(nil),                            // 12: iterm2.SessionSummary
	(*CreateTabRequest)(nil),                          // 13: iterm2.CreateTabRequest
	(*CreateTabResponse)(nil),                         // 14: iterm2.CreateTabResponse
	(*SendTextRequest)(nil),                           // 15: iterm2.SendTextRequest
	(*SendTextResponse)(nil),                          // 16: iterm2.SendTextResponse
	(*ActivateRequest)(nil),                           // 17: iterm2.ActivateRequest
	(*ActivateResponse)(nil),                          // 18: iterm2.ActivateResponse
	(*GetBufferRequest)(nil),                          // 19: iterm2.GetBufferRequest
	(*LineRange)(nil),                                 // 20: iterm2.LineRange
	(*GetBufferResponse)(nil),                         // 21: iterm2.GetBufferResponse
	(*LineContents)(nil),                              // 22: iterm2.LineContents
	(*VariableRequest)(nil),                           // 23: iterm2.VariableRequest
	(*VariableResponse)(nil),                          // 24: iterm2.VariableResponse
	(*FocusRequest)(nil),                              // 25: iterm2.FocusRequest
	(*FocusResponse)(nil),                             // 26: iterm2.FocusResponse
	(*FocusChangedNotification)(nil),                  // 27: iterm2.FocusChangedNotification
	(*ListSessionsResponse_Window)(nil),               // 28: iterm2.ListSessionsResponse.Window
	(*ListSessionsResponse_Tab)(nil),                  // 29: iterm2.ListSessionsResponse.Tab
	(*SplitTreeNode_SplitTreeLink)(nil),               // 30: iterm2.SplitTreeNode.SplitTreeLink
	(*FocusChangedNotification_Window)(nil),           // 31: iterm2.FocusChangedNotification.Window
}
var file_internal_terminal_iterm_proto_api_proto_depIdxs = []int32{
	19, // 0: iterm2.ClientOriginatedMessage.get_buffer_request:type_name -> iterm2.GetBufferRequest
	9,  // 1: iterm2.ClientOriginatedMessage.list_sessions_request:type_name -> iterm2.ListSessionsRequest
	15, // 2: iterm2.ClientOriginatedMessage.send_text_request:type_name -> iterm2.SendTextRequest
	13, // 3: iterm2.ClientOriginatedMessage.create_tab_request:type_name -> iterm2.CreateTabRequest
	17, // 4: iterm2.ClientOriginatedMessage.activate_request:type_name -> iterm2.ActivateRequest
	23, // 5: iterm2.ClientOriginatedMessage.variable_request:type_name -> iterm2.VariableRequest
	25, // 6: iterm2.ClientOriginatedMessage.focus_request:type_name -> iterm2.FocusRequest
	21, // 7: iterm2.ServerOriginatedMessage.get_buffer_response:type_name -> iterm2.GetBufferResponse
	10, // 8: iterm2.ServerOriginatedMessage.list_sessions_response:type_name -> iterm2.ListSessionsResponse
	16, // 9: iterm2.ServerOriginatedMessage.send_text_response:type_name -> iterm2.SendTextResponse
	14, // 10: iterm2.ServerOriginatedMessage.create_tab_response:type_name -> iterm2.CreateTabResponse
	18, // 11: iterm2.ServerOriginatedMessage.activate_response:type_name -> iterm2.ActivateResponse
	24, // 12: iterm2.ServerOriginatedMessage.variable_response:type_name -> iterm2.VariableResponse
	26, // 13: iterm2.ServerOriginatedMessage.focus_response:type_name -> iterm2.FocusResponse
	8,  // 14: iterm2.ServerOriginatedMessage.notification:type_name -> iterm2.Notification
	28, // 15: iterm2.ListSessionsResponse.windows:type_name -> iterm2.ListSessionsResponse.Window
	30, // 16: iterm2.SplitTreeNode.links:type_name -> iterm2.SplitTreeNode.SplitTreeLink
	0,  // 17: iterm2.CreateTabResponse.status:type_name -> iterm2.CreateTabResponse.Status
	1,  // 18: iterm2.SendTextResponse.status:type_name -> iterm2.SendTextResponse.Status
	2,  // 19: iterm2.ActivateResponse.status:type_name -> iterm2.ActivateResponse.Status
	20, // 20: iterm2.GetBufferRequest.line_range:type_name -> iterm2.LineRange
	3,  // 21: iterm2.GetBufferResponse.status:type_name -> iterm2.GetBufferResponse.Status
	22, // 22: iterm2.GetBufferResponse.contents:type_name -> iterm2.LineContents
	4,  // 23: iterm2.VariableResponse.status:type_name -> iterm2.VariableResponse.Status
	27, // 24: iterm2.FocusResponse.notifications:type_name -> iterm2.FocusChangedNotification
	31, // 25: iterm2.FocusChangedNotification.window:type_name -> iterm2.FocusChangedNotification.Window
	29, // 26: iterm2.ListSessionsResponse.Window.tabs:type_name -> iterm2.ListSessionsResponse.Tab
	11, // 27: iterm2.ListSessionsResponse.Tab.root:type_name -> iterm2.SplitTreeNode
	12, // 28: iterm2.SplitTreeNode.SplitTreeLink.session:type_name -> iterm2.SessionSummary
	11, // 29: iterm2.SplitTreeNode.SplitTreeLink.node:type_name -> iterm2.SplitTreeNode
	5,  // 30: iterm2.FocusChangedNotification.Window.window_status:type_name -> iterm2.FocusChangedNotification.Window.WindowStatus
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_internal_terminal_iterm_proto_api_proto_init() }
func file_internal_terminal_iterm_proto_api_proto_init() {
	if File_internal_terminal_iterm_proto_api_proto != nil {
		return
	}
	file_internal_terminal_iterm_proto_api_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientOriginatedMessage_GetBufferRequest)(nil),
		(*ClientOriginatedMessage_ListSessionsRequest)(nil),
		(*ClientOriginatedMessage_SendTextRequest)(nil),
		(*ClientOriginatedMessage_CreateTabRequest)(nil),
		(*ClientOriginatedMessage_ActivateRequest)(nil),
		(*ClientOriginatedMessage_VariableRequest)(nil),
		(*ClientOriginatedMessage_FocusRequest)(nil),
	}
	file_internal_terminal_iterm_proto_api_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerOriginatedMessage_Error)(nil),
		(*ServerOriginatedMessage_GetBufferResponse)(nil),
		(*ServerOriginatedMessage_ListSessionsResponse)(nil),
		(*ServerOriginatedMessage_SendTextResponse)(nil),
		(*ServerOriginatedMessage_CreateTabResponse)(nil),
		(*ServerOriginatedMessage_ActivateResponse)(nil),
		(*ServerOriginatedMessage_VariableResponse)(nil),
		(*ServerOriginatedMessage_FocusResponse)(nil),
		(*ServerOriginatedMessage_Notification)(nil),
	}
	file_internal_terminal_iterm_proto_api_proto_msgTypes[11].OneofWrappers = []any{
		(*ActivateRequest_WindowId)(nil),
		(*ActivateRequest_TabId)(nil),
		(*ActivateRequest_SessionId)(nil),
	}
	file_internal_terminal_iterm_proto_api_proto_msgTypes[17].OneofWrappers = []any{
		(*VariableRequest_SessionId)(nil),
		(*VariableRequest_TabId)(nil),
		(*VariableRequest_App)(nil),
		(*VariableRequest_WindowId)(nil),
	}
	file_internal_terminal_iterm_proto_api_proto_msgTypes[21].OneofWrappers = []any{
		(*FocusChangedNotification_ApplicationActive)(nil),
		(*FocusChangedNotification_Window_)(nil),
		(*FocusChangedNotification_SelectedTab)(nil),
		(*FocusChangedNotification_Session)(nil),
	}
	file_internal_terminal_iterm_proto_api_proto_msgTypes[24].OneofWrappers = []any{
		(*SplitTreeNode_SplitTreeLink_Session)(nil),
		(*SplitTreeNode_SplitTreeLink_Node)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_terminal_iterm_proto_api_proto_rawDesc), len(file_internal_terminal_iterm_proto_api_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_terminal_iterm_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_terminal_iterm_proto_api_proto_depIdxs,
		EnumInfos:         file_internal_terminal_iterm_proto_api_proto_enumTypes,
		MessageInfos:      file_internal_terminal_iterm_proto_api_proto_msgTypes,
	}.Build()
	File_internal_terminal_iterm_proto_api_proto = out.File
	file_internal_terminal_iterm_proto_api_proto_goTypes = nil
	file_internal_terminal_iterm_proto_api_proto_depIdxs = nil
}
